name: feriasjeri_app
description: "Férias Jeri"
publish_to: "https://feriasjeri.web.app/"

version: 1.0.0+1 # Versão do app no formato major.minor.patch+build_number

environment:
  sdk: ">=3.5.4 <4.0.0" # Define o intervalo de versões suportadas do Dart SDK

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations: # Para suporte à localização (ex.: traduções)
    sdk: flutter

  # Ícones e UI
  cupertino_icons: ^1.0.8 # Ícones padrão para apps Cupertino (estilo iOS)
  flutter_login: ^5.0.0 # Biblioteca para telas de login

  # Firebase
  firebase_core: ^3.8.0 # Integração com o Firebase
  firebase_auth: ^5.3.3 # Autenticação do Firebase
  cloud_firestore: ^5.5.0 # Banco de dados Firestore

  # Gerenciamento de estado e UI
  provider: ^6.1.2 # Gerenciamento de estado baseado em InheritedWidget
  modal_bottom_sheet: ^3.0.0 # Modal customizável para bottom sheets
  calendar_date_picker2: ^1.1.7 # Picker de datas personalizável

  # Internacionalização e formatação
  intl: ^0.19.0 # Para formatação de datas, números e strings localizadas

dev_dependencies:
  # Testes e lint
  flutter_test:
    sdk: flutter # Ferramentas para testes unitários e de integração
  flutter_lints: ^4.0.0 # Regras padrão de lint para projetos Flutter

flutter:
  uses-material-design: true # Ativa o uso de ícones Material Design

  assets:
    - assets/images/background.jpg # Adiciona imagem usada no projeto
